In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Answer - Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list data type, whereas the variable array_list is a NumPy array data type.

To print the data types of both variables, I can use the built-in type() function in Python as follows:

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Here, the first print statement prints the data type of list_ as <class 'list'> which confirms that list_ is a Python list object. The second print statement prints the data type of array_list as <class 'numpy.ndarray'> which confirms that array_list is a NumPy array object.

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [6]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

for element in list_:
    print(type(element))
    
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Answer 3. Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list when the code array_list = np.array(object=list_, dtype=int) is executed.

The dtype=int argument specifies that the elements in array_list should be converted to integers. Therefore, the data type of the elements in array_list will be changed from numpy.str_ to numpy.int64.

To print the data types of each and every element present in both the variables list_ and array_list, we can use a loop and the type() function as follows:

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)


for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


for sublist in num_list:
    for element in sublist:
        print(type(element))


for element in num_array.flat:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

Answer. To find the characteristics of the variable num_array, we can use the following NumPy array attributes:

1. shape: returns a tuple of integers representing the dimensions of the array.
2. size: returns the total number of elements in the array.


Here is the code to find the shape and size of num_array:

In [10]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)


print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
import numpy as np

zeros_array = np.zeros((3,3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
